#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/users/students/r0582625/Documents/thesis/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/users/students/r0582625/Documents/thesis/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/users/students/r0582625/Documents/neural-simulation/v1/components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
