#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/users/mns/lapolina/miniconda3/envs/bmtk/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/users/mns/lapolina/miniconda3/envs/bmtk/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/users/mns/lapolina/Desktop/bmtk-release-v1.0.0/docs/examples/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
